### ISSUE TITLE
can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu()

### ISSUE THREAD

**Issue by samyeh0527** [WongKinYiu/yolor#113]
Hi WongKinYiu ,
when training is the end will show some issues but my environment python is [3.9] didn't know the version difference is the main reason for this .

As just mentioned  Error issues [ can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to cpoy the tensor to host memory first  ]

I know the numpy is cpu only  but how can i fix this issues ?  

wish you a nice day

**Comment by WongKinYiu** [comment]
Use Tensor.cpu() to cpoy the tensor to host memory first.

**Comment by samyeh0527** [comment]
Traceback (most recent call last):
  File "/home/umeida/Desktop/yolor/train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "/home/umeida/Desktop/yolor/train.py", line 336, in train
    results, maps, times = test.test(opt.data,
  File "/home/umeida/Desktop/yolor/test.py", line 226, in test
    plot_images(img, output_to_target(output, width, height), paths, f, names)  # predictions
  File "/home/umeida/Desktop/yolor/utils/plots.py", line 108, in output_to_target
    return np.array(targets)   
  File "/home/umeida/anaconda3/envs/yolor/lib/python3.9/site-packages/torch/_tensor.py", line 643, in __array__
    return self.numpy()   <-------Replace  Tensor.cpu(targets)  ?

**Comment by WongKinYiu** [comment]
return self.cpu().numpy()

**Comment by samyeh0527** [comment]
Thanks ,  we change the 840e56e can fix this issue . it's work successful

**Comment by danielcrane** [comment]
Is there any reason this change isn't being merged to the main branches?

**Comment by samyeh0527** [comment]
may be just  rarely happens

**Comment by MehmetAlpkaya** [comment]
ı have same error, but ı dont solution error can you halp me?

def dist(args, model, device, train_loader, fea_loader, tar_loader, centers):
    model.eval()
    dizi=[]
    d0 = []
    d1 = []
    d2 = []
    d3 = []

    mean_d0 = 0
    mean_d1 = 0
    mean_d2 = 0
    mean_d3 = 0

    var_d0 = 0
    var_d1 = 0
    var_d2 = 0
    var_d3 = 0

    with torch.no_grad():
        for batch_idx, data in enumerate(train_loader):
            sample = data[:, 0:784]
            #print("sample:{}".format(sample))
            target = data[:, 784:785]
            #print("target:{}".format(target))
            sample = sample.reshape((-1, 1, 28, 28))
            #print("sample:{}".format(sample))
            sample = Variable(torch.from_numpy(sample))
            #print("sample:{}".format(sample))
            sample = sample.cuda()
           # print("sample:{}".format(sample))
            sample = sample.type(torch.cuda.FloatTensor)
            #print("sample:{}".format(sample))
            target = Variable(torch.from_numpy(target))
            #print("target:{}".format(target))
            target = target.view(64)
            #print("target:{}".format(target))
            target = target.cuda()
            #print("target:{}".format(target))
            target = target.type(torch.cuda.LongTensor)
            #print("target:{}".format(target))

            fea, output = model(sample) #[64,2]
            #print("fea:{}".format(fea))
            fea_loader.append(fea)
            #print("fea_loader:{}".format(fea_loader))
            tar_loader.append(target)
            #print("tar_loader:{}".format(fea_loader))

            expanded_centers = centers.expand(64, -1, -1)  # [64,4,2]
           # print("expanded_centers:{}".format(expanded_centers))
            expanded_feature = fea.expand(4, -1, -1).transpose(1, 0)  # [64,4,2]
            #print("expanded_feature:{}".format(expanded_feature))
            distance_centers = (expanded_feature - expanded_centers).pow(2).sum(dim=-1)  # [64,4]
            #print("distance_centers:{}".format(distance_centers))
            
            for i in range(0, 64):
                if target[i]==0:
                    d0.append(distance_centers[i,0]**0.5)
                if target[i]==1:
                    d1.append(distance_centers[i,1]**0.5)
                if target[i]==2:
                    d2.append(distance_centers[i,2]**0.5)
                if target[i]==3:
                    d3.append(distance_centers[i,3]**0.5)
    #print(len(d0))
    mean_d0 = np.mean(d0)  #i am getting the error here
    mean_d1 = np.mean(d1)
    mean_d2 = np.mean(d2)
    mean_d3 = np.mean(d3)
 
    var_d0 = np.std(d0)
    var_d1 = np.std(d1)
    var_d2 = np.std(d2)
    var_d3 = np.std(d3)

    return mean_d0,mean_d1,mean_d2,mean_d3,var_d0,var_d1,var_d2,var_d3
