### ISSUE TITLE
执行detect.py，使用自己训练好的权重检测一段.mp4视频报错

### ISSUE THREAD

**Issue by Wanghe1997** [WongKinYiu/yolor#12]
作者你好，继上次我使用自己的数据集训练好网络后，想使用训练好的权重检测一段mp4视频，但是报错了。视频为test.mp4，我放在和detct.py同级的目录下，运行指令如下：
python detect.py --source test.mp4 --cfg cfg/yolor_p6_puxiang.cfg --weights runs/train/exp3/weights/last_998.pt --conf 0.25 --img-size 1280 --device 0
报错如下：
Traceback (most recent call last):
  File "detect.py", line 186, in <module>
    detect()
  File "detect.py", line 44, in detect
    model.load_state_dict(torch.load(weights[0], map_location=device)['model'])
  File "D:\Software\Anaconda3\envs\YOLOR\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Software\Anaconda3\envs\YOLOR\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Software\Anaconda3\envs\YOLOR\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'y'

请问是否是yoloR不支持检测视频，只支持检测图片？还是我环境配置的问题呢?谢谢

**Comment by alt-Pranav** [comment]
How did you resolve this issue? I'm facing the exact same problem
