### ISSUE TITLE
Train with branch paper

### ISSUE THREAD

**Issue by linghu8812** [WongKinYiu/yolor#22]
Hello! When I finish training with branch paper, it encountered with an error:
```bash
  File "train.py", line 562, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 369, in train
    log_imgs=opt.log_imgs if wandb else 0)
  File "/home/linghu8812/yolor_ele/test.py", line 211, in test
    plot_images(img, output_to_target(output, width, height), paths, f, names)  # predictions
  File "/home/linghu8812/yolor_ele/utils/plots.py", line 108, in output_to_target
    return np.array(targets)
  File "/media/D/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

```
perhaps it should be this?
```python
 return np.array(targets.cpu())
```

**Comment by WongKinYiu** [comment]
Yes, it can solve the problem. https://github.com/WongKinYiu/yolor/issues/16#issuecomment-853717447

**Comment by danielcrane** [comment]
I noticed the same thing - would it help if I sent a pull request to the `paper` branch to fix this issue @WongKinYiu ?

**Comment by Nikunjbansal99** [comment]
> ```python
> cpu()
> ```

Traceback (most recent call last):
  File "test.py", line 330, in <module>
    save_conf=opt.save_conf,
  File "test.py", line 226, in test
    plot_images(img, output_to_target(output, width, height), paths, f, names)  # predictions
  File "/content/yolor/utils/plots.py", line 108, in output_to_target
    return np.array(targets.cpu())
AttributeError: 'list' object has no attribute 'cpu'
