### ISSUE TITLE
test.py Error 

### ISSUE THREAD

**Issue by Minseokkim-0124** [WongKinYiu/yolor#227]
I trained the model with my custom dataset and I am trying to get a test evaluation. But, I have some problems.

`!python test.py --data ./test.yaml --img 416 --batch 32 --device 0 --cfg ./cfg/yolor_p6.cfg --weights /content/drive/MyDrive/best.pt `

I got errors like below

Traceback (most recent call last):
  File "test.py", line 330, in <module>
    save_conf=opt.save_conf,
  File "test.py", line 226, in test
    plot_images(img, output_to_target(output, width, height), paths, f, names)  # predictions
  File "/content/yolor/utils/plots.py", line 108, in output_to_target
    return np.array(targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Plus I want to know if I use 416 image size, WARNING: --img-size 416 must be multiple of max stride 64, updating to 448 occurs. How can I solve this?

**Comment by Nikunjbansal99** [comment]
Facing the Same Issue. If I am running a test.py script on the CPU. It is running fine. Got this Error on GPU Tesla P-100.

**Comment by Nikunjbansal99** [comment]
Any solution??

**Comment by Minseokkim-0124** [comment]
thx for your help^^
