### ISSUE TITLE
What should I do when testing doesn't work with pycocotools?

### ISSUE THREAD

**Issue by cnr0724** [WongKinYiu/yolor#27]
```
               Class      Images     Targets           P           R      mAP@.5
               Class      Images     Targets           P           R      mAP@.5
               Class      Images     Targets           P           R      mAP@.5
               Class      Images     Targets           P           R      mAP@.5
               Class      Images     Targets           P           R      mAP@.5
               Class      Images     Targets           P           R      mAP@.5
  mAP@.5:.95: 100%|█| 18/18 [00:14<00:00,  1.89it/s]
                 all         548    3.88e+04       0.377       0.559       0.488       0.309
Speed: 8.8/4.6/13.4 ms inference/NMS/total per 1280x1280 image at batch-size 32

Evaluating pycocotools mAP... saving runs/test/yolor_p6_val8/best_ap_predictions.json...
loading annotations into memory...
ERROR: pycocotools unable to run: expected str, bytes or os.PathLike object, not list
Results saved to runs/test/yolor_p6_val8
```
This is what I get while testing. What should I do when this happens?

**Comment by WongKinYiu** [comment]
check if your ground truth file is here: https://github.com/WongKinYiu/yolor/blob/main/test.py#L260

**Comment by cnr0724** [comment]
I checked it, thanks. But I get
```
Traceback (most recent call last):
  File "test.py", line 330, in <module>
    save_conf=opt.save_conf,
  File "test.py", line 260, in test
    anno_json = glob.glob('../coco/annotations/instances_val*.json')[0]  # annotations json
IndexError: list index out of range
```
this error....

**Comment by WongKinYiu** [comment]
list index out of range means that the ground truth file is not here.

**Comment by cnr0724** [comment]
Okay....Thanks for the great work by the way. I'll find a way to figure it out.

**Comment by MheadHero** [comment]
> Okay....Thanks for the great work by the way. I'll find a way to figure it out.

how you settle it?

**Comment by Ahmad-mahdi** [comment]
How can I stop code from saving JSON?
