### ISSUE TITLE
AssertionError: No labels found in ../train/labels/. 

### ISSUE THREAD

**Issue by SamratSahoo** [WongKinYiu/yolor#36]
I am currently using this repository in a Colab notebook on a custom dataset but when I try running the training script, I keep getting the following error: 

```
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 183, in train
    rank=rank, world_size=opt.world_size, workers=opt.workers)
  File "/content/yolor/utils/datasets.py", line 72, in create_dataloader
    rank=rank)
  File "/content/yolor/utils/datasets.py", line 499, in __init__
    assert not augment, '%s. Can not train without labels.' % s
AssertionError: WARNING: No labels found in ../train/labels/. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data. Can not train without labels.
```

I know for a fact that my dataset structure is formatted correctly and I do have labels in my `train/labels/` folder so I was unsure what could be causing this issue. My folder structure looks something like this:
<img width="184" alt="fldr-structure" src="https://user-images.githubusercontent.com/44482993/124154611-45088f00-da5b-11eb-90cc-5899de9ce82e.PNG">
For reference, I am running the following command to start the training process:

`python train.py --batch-size 8 --img 416 416 --data /content/data.yaml --cfg cfg/yolor_p6.cfg --weights '' --device 0 --name yolor_p6 --hyp hyp.scratch.1280.yaml --epochs 300`

And my `data.yaml` file looks like this:
```
train: ../train/images
val: ../valid/images

nc: 3
names: ['Crab', 'Lobster', 'Shrimp']
```
Any and all help would be appreciated; thank you!

**Comment by SamratSahoo** [comment]
Fixed by changing this line:
https://github.com/WongKinYiu/yolor/blob/2fa3a318f364a4eb58721c90e5a978a78f0da58a/utils/datasets.py#L372

To:
```
return [x.replace('images', 'labels').replace(os.path.splitext(x)[-1], '.txt') for x in img_paths]
```

This happened because the label filenames had multiple periods (i.e. `BloodImage_00001_jpg.rf.1a3206b15602db1d97193162a50bd001.txt`) so the split didn't work as intended.
