### ISSUE TITLE
colab train problem

### ISSUE THREAD

**Issue by tturkmen** [WongKinYiu/yolor#4]
!python train.py --data ./data/uav_coco.yaml --batch-size 8 --cfg ./models/uav_e6.yaml --name yolor-p6 --weights ""  --hyp ./data/hyp.scratch.1280.yaml
i have some problems
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 86, in train
    model = Darknet(opt.cfg).to(device) # create
  File "/content/yolor/models/models.py", line 530, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "/content/yolor/utils/parse_config.py", line 13, in parse_model_cfg
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './models/uav_e6.yaml.cfg'

**Comment by WongKinYiu** [comment]
It seems you are using yaml style network config while the main branch only accept darknet style network config.
Please try this branch https://github.com/WongKinYiu/yolor/tree/paper

Or if your are using darknet style network config, you have typos.
`--cfg ./models/uav_e6.yaml` -> `--cfg ./models/uav_e6.cfg`
