### ISSUE TITLE
non_max_suppression causes CUDA out of memory.

### ISSUE THREAD

**Issue by ixez** [WongKinYiu/yolor#41]
I am training yolor with crowdhuman dataset. Even the train and test batch sizes are set to 1, the program still encounters memory problems when testing (I got 12G memory). I found it is due to `non_max_suppression`, anyone has the same problem?

```
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
File "train.py", line 336, in train
results, maps, times = test.test(opt.data,
File "/workplace/Codes/yolor/test.py", line 134, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres)
File "/workplace/Codes/yolor/utils/general.py", line 341, in non_max_suppression
i = torch.ops.torchvision.nms(boxes, scores, iou_thres)
RuntimeError: CUDA out of memory. Tried to allocate 10.49 GiB (GPU 0; 10.91 GiB total capacity; 618.68 MiB already allocated; 6.45 GiB free; 3.78 GiB reserved in total by PyTorch) 
```

**Comment by trungpham2606** [comment]
@ixez 
I have the same problem with you, but then I can train the model by setting the value of rect in here to store_false.
![image](https://user-images.githubusercontent.com/35657426/125880615-c3d98d0f-ba9c-4ae2-8f95-c8c0c6385d8c.png)
But the problem is after nearly 100 epochs; during inference, the model outputs nothing at all.

**Comment by WongKinYiu** [comment]
you could increase epoch number for start test
https://github.com/WongKinYiu/yolor/blob/main/train.py#L335

or pass `conf_thres=0.1` into test function
https://github.com/WongKinYiu/yolor/blob/main/train.py#L336

**Comment by trungpham2606** [comment]
Dear @WongKinYiu ,
I have a question, the rect option is set to False as default, so what is the difference between setting it to False or True ?
And when set it to False, I cant train the yolor because of OOM.
I had set the conf_thres=0.0001, the results are so random. The loss during training was around 0.02

**Comment by WongKinYiu** [comment]
--rect is not suggested to use due to it do not shuffle data in default.
with --rect: no mosaic augmentation, so the gt will be ~1/4, and the memory used for compute loss will reduce to 1/4.

**Comment by trungpham2606** [comment]
@WongKinYiu 
So with 11Gb memory of card, how can I do to be able to train the yolor ?

**Comment by ixez** [comment]
@WongKinYiu 
Thanks for the reply.
Starting testing early doesn't solve the problem, but delays it.
![image](https://user-images.githubusercontent.com/1274945/125882995-c8d8646d-6680-41f1-8676-618e8213d2b9.png)

Any other insights about the cause?

**Comment by trungpham2606** [comment]
Oh you have so many objects in 1 image @ixez

**Comment by ixez** [comment]
@WongKinYiu Regarding the second advice, is the problem caused by too many bboxes when testing?

**Comment by janchk** [comment]
> @WongKinYiu Regarding the second advice, is the problem caused by too many bboxes when testing?

Yes. I figured out that it is. 
To fix this you could uncomment this lline
https://github.com/WongKinYiu/yolor/blob/b168a4dd0fe22068bb6f43724e22013705413afb/utils/general.py#L336
And add some clipping for reasonable amount of predictions for example
`
x = x[0:10000, :]
`
