### ISSUE TITLE
关于plot_images的索引超出范围的问题

### ISSUE THREAD

**Issue by LaoGanGit** [WongKinYiu/yolor#52]
作者你好，我在运行我自己的数据集，到了最后一个epoch时，出现了下面的错误
Traceback (most recent call last):
  File "F:/jinyuan/yolor-main/train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "F:/jinyuan/yolor-main/train.py", line 344, in train
    log_imgs=opt.log_imgs if wandb else 0)
  File "F:\jinyuan\yolor-main\test.py", line 226, in test
    plot_images(img, output_to_target(output, width, height), paths, f, names)  # predictions
  File "F:\jinyuan\yolor-main\utils\plots.py", line 163, in plot_images
    cls = names[cls] if names else cls
IndexError: list index out of range
因为这个问题，导致最后在run里面少了很多图片，没有mAp的曲线图

请教，这是什么原因导致的呢，有何解决的方法，谢谢

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolor/blob/main/test.py#L312
這裡要改成您的names fiile

**Comment by LaoGanGit** [comment]
> https://github.com/WongKinYiu/yolor/blob/main/test.py#L312
> 這裡要改成您的names fiile

好的，非常感谢您的解答

**Comment by LaoGanGit** [comment]
> https://github.com/WongKinYiu/yolor/blob/main/test.py#L312
> 這裡要改成您的names fiile
作者您好，我按您的建议修改了下还是出现原来的错误，您看下我这个自定的names.file和yaml有问题吗？
是否除了test.py的names修改外还有哪些跟着修改呢？
另外detect.py#176的names我也修改成跟test.py一样的路径和内容了
![1627202452(1)](https://user-images.githubusercontent.com/74133146/126893145-9b4d844d-9742-481c-ae83-053c82bf012c.jpg)
![image](https://user-images.githubusercontent.com/74133146/126893375-ac82c65d-60e3-412a-a7d9-8e6c27691f33.png)
![image](https://user-images.githubusercontent.com/74133146/126893396-c25bfb27-e4d2-40d9-bb3a-72ec8a6fe58e.png)
![image](https://user-images.githubusercontent.com/74133146/126893413-71e2dce6-7458-41a7-9ef8-d8d801d0875e.png)

**Comment by Hu-nie** [comment]
hello

I have the same problem. Did you figure it out?

**Comment by Hu-nie** [comment]
I solved this problem.

https://github.com/WongKinYiu/yolor/pull/17

**Comment by wgggSg** [comment]
请问你解决掉这个问题了吗？我也遇到了相同的问题

**Comment by francesco-taioli** [comment]
I also have this problem even if I create a custom `data.names` file with the correct label

**Comment by yydc-0** [comment]
I have the same problem. Did you figure it out?

**Comment by WenTianWuHuo** [comment]
You need to change the. cfg file you are using, changing 'classes=80' to 'classes=yours  classes' and' filters=225 'to' filters=(5+yours  classes) * 3 '.
