### ISSUE TITLE
image size attribut not working

### ISSUE THREAD

**Issue by abdelhak51** [WongKinYiu/yolor#53]
hi, when I change    --img-size  from 1280  to 320 for example it is not working and throws me an error which is  : 

Traceback (most recent call last):
  File "detect.py", line 187, in <module>
    detect()
  File "detect.py", line 86, in detect
    pred = model(img, augment=opt.augment)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ASUS\Desktop\yoloR\yolor\models\models.py", line 543, in forward
    return self.forward_once(x)
  File "C:\Users\ASUS\Desktop\yoloR\yolor\models\models.py", line 594, in forward_once
    x = module(x, out)  # WeightedFeatureFusion(), FeatureConcat()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ASUS\Desktop\yoloR\yolor\utils\layers.py", line 69, in forward
    return torch.cat([outputs[i] for i in self.layers], 1) if self.multiple else outputs[self.layers[0]]
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 15 and 16 in dimension 2 (The offending index is 1)

any solution for this problem .

**Comment by WongKinYiu** [comment]
input size should be 128x for p6 models.

**Comment by abdelhak51** [comment]
thank you @WongKinYiu  I solved the problem so I found that  --img-size  accepts  64  , 320 only
