### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'y'

### ISSUE THREAD

**Issue by Zomcxj** [WongKinYiu/yolor#66]
作者你好，我在运行一开始检测时
python detect.py --source inference/images/horses.jpg --cfg cfg/yolor_p6.cfg --weights yolor_p6.pt --conf 0.25 --img-size 1280 --device 0时出现了这种错误
Traceback (most recent call last):
  File "E:/DeepLearning/Py-YOLOR/YOLOR-cat/detect.py", line 186, in <module>
    detect()
  File "E:/DeepLearning/Py-YOLOR/YOLOR-cat/detect.py", line 44, in detect
    model.load_state_dict(torch.load(weights[0], map_location=device)['model'])
  File "D:\JetBrains\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\JetBrains\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\JetBrains\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'y'
请问是什么原因？

**Comment by Zomcxj** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'E'
我把各种路径补全就变成了这个错误

**Comment by Zomcxj** [comment]
> 作者你好，我在运行一开始检测时
> python detect.py --source inference/images/horses.jpg --cfg cfg/yolor_p6.cfg --weights yolor_p6.pt --conf 0.25 --img-size 1280 --device 0时出现了这种错误
> Traceback (most recent call last):
> File "E:/DeepLearning/Py-YOLOR/YOLOR-cat/detect.py", line 186, in
> detect()
> File "E:/DeepLearning/Py-YOLOR/YOLOR-cat/detect.py", line 44, in detect
> model.load_state_dict(torch.load(weights[0], map_location=device)['model'])
> File "D:\JetBrains\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 579, in load
> with _open_file_like(f, 'rb') as opened_file:
> File "D:\JetBrains\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
> return _open_file(name_or_buffer, mode)
> File "D:\JetBrains\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 211, in **init**
> super(_open_file, self).**init**(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'y'
> 请问是什么原因？
