### ISSUE TITLE
nms error while training

### ISSUE THREAD

**Issue by cnr0724** [WongKinYiu/yolor#70]
```
     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      0/99     1.61G   0.03214   0.01845         0   0.05059        20       320

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      1/99     1.73G   0.03125   0.01528         0   0.04654        56       320

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      2/99     1.73G   0.02886   0.01622         0   0.04508        57       320

     Epoch   gpu_mem       box       obj       cls     total   targets  img_size
      3/99     1.73G   0.02585   0.01663         0   0.04248        53       320
               Class      Images     Targets           P           R      mAP@.5
Traceback (most recent call last):
  File "train.py", line 536, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 343, in train
    log_imgs=opt.log_imgs if wandb else 0)
  File "/home/dnaplus/Downloads/yolor/test.py", line 134, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres)
  File "/home/dnaplus/Downloads/yolor/utils/general.py", line 341, in non_max_suppression
    i = torch.ops.torchvision.nms(boxes, scores, iou_thres)
  File "/home/dnaplus/.local/lib/python3.6/site-packages/torch/_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torchvision::nms

```

What should I do to solve this problem? I'm currently running the training process on Jetson nano xavier NX.

**Comment by cnr0724** [comment]
my env
torch=1.8.0+cu102

**Comment by cnr0724** [comment]
I guess running the training process on Jetson nano was the problem.
