### ISSUE TITLE
Non-normalized or out of bounds coordinate labels

### ISSUE THREAD

**Issue by FXY0117** [WongKinYiu/yolor#93]
Namespace(adam=False, batch_size=1, bucket='', cache_images=False, cfg='./cfg/yolor_p6.cfg', data='./data/coco128.yaml', device='0', epochs=50, evolve=False, exist_ok=False, global_rank=-1, hyp='./data/hyp.scratch.1280.yaml', image_weights=False, img_size=[1280, 720], local_rank=-1, log_imgs=16, multi_scale=False, name='yolor_p6', noautoanchor=False, nosave=True, notest=False, project='runs/train', rect=False, resume=False, save_dir='runs/train/yolor_p611', single_cls=False, sync_bn=False, total_batch_size=1, weights='./weights/yolor_p6.pt', workers=0, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/train", view at http://localhost:6006/
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.05, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 0.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.5, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}
Model Summary: 665 layers, 36876216 parameters, 36876216 gradients, 80.471037400 GFLOPS
Transferred 850/862 items from ./weights/yolor_p6.pt
Optimizer groups: 145 .bias, 145 conv.weight, 149 other
WARNING: --img-size 1080 must be multiple of max stride 64, updating to 1088
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 181, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/home/zbb/yolor/utils/datasets.py", line 64, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/zbb/yolor/utils/datasets.py", line 451, in __init__
    assert (l[:, 1:] <= 1).all(), 'non-normalized or out of bounds coordinate labels: %s' % file
AssertionError: non-normalized or out of bounds coordinate labels: data/drink/train/labels/15512618944192.txt

It seems that some questions in my own training data，I don know how to solve it.

**Comment by WongKinYiu** [comment]
box label should be normalized by image width and height.

**Comment by FXY0117** [comment]
> 框标签应按图像宽度和高度进行归一化。
But I have trained successfully on yolov5 in the same datasets, so is there some differences between yolov5 and yolor in data  labeling？

**Comment by WongKinYiu** [comment]
well, i guess you modify the code for your success training.
you could just command the line `File "/home/zbb/yolor/utils/datasets.py", line 451` to ignore this checking.

**Comment by FXY0117** [comment]
> well, i guess you modify the code for your success training.
> you could just command the line `File "/home/zbb/yolor/utils/datasets.py", line 451` to ignore this checking

> well, i guess you modify the code for your success training.
> you could just command the line `File "/home/zbb/yolor/utils/datasets.py", line 451` to ignore this checking.

Thanks first, and you mean that I can notes this code for my success training?
